version: '3.8'
services:
  web:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - php
  php:
    build: .
    volumes:
      - ./html:/var/www/html
